apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-mysql
spec:
  selector:
    matchLabels:
      app: k8s-springboot-mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-springboot-mysql
    spec:
      containers:
        - name: k8s-springboot-mysql
          image: k8s-springboot-mysql:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: host
          
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: dbName
          
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-encrypt
                  key: username
          
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-encrypt
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-mysql-service
spec:
  selector:
    app: k8s-springboot-mysql
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort